image: node:13.5.0

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install -g @angular/cli@8.3.25
  - npm install
  - npm run build 
  artifacts:
    paths:
    - public
  only:
  - master
  - pages